---
project_name: professorit
project_root: /srv/professorit
releases_to_keep: 5
timezone: Europe/Moscow

app_api_upstream: http://professorit-api:8000
app_frontend_upstream: http://professorit-frontend:80
runtime_network: professorit_runtime

site_container_image: nginx:1.30-alpine
tls_contact_email: moiseenko.business@mail.ru
